name: socket_connector
description: Connect two TCP sockets and optionally display the traffic.

version: 1.0.1
repository: https://github.com/cconstab/socket_connector

environment:
  sdk: '>=2.19.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  chalkdart: ^2.0.9
